#include "StringToAssimpTypeTransfer.hpp"

const std::unordered_map<std::string, uint32_t> AirEngine::Runtime::Utility::StringToAssimpTypeTransfer::AI_POST_PROCESS_STEPS_MAP
{
	{ "aiProcess_CalcTangentSpace", aiProcess_CalcTangentSpace },
	{ "aiProcess_JoinIdenticalVertices", aiProcess_JoinIdenticalVertices },
	{ "aiProcess_MakeLeftHanded", aiProcess_MakeLeftHanded },
	{ "aiProcess_Triangulate", aiProcess_Triangulate },
	{ "aiProcess_RemoveComponent", aiProcess_RemoveComponent },
	{ "aiProcess_GenNormals", aiProcess_GenNormals },
	{ "aiProcess_GenSmoothNormals", aiProcess_GenSmoothNormals },
	{ "aiProcess_SplitLargeMeshes", aiProcess_SplitLargeMeshes },
	{ "aiProcess_PreTransformVertices", aiProcess_PreTransformVertices },
	{ "aiProcess_LimitBoneWeights", aiProcess_LimitBoneWeights },
	{ "aiProcess_ValidateDataStructure", aiProcess_ValidateDataStructure },
	{ "aiProcess_ImproveCacheLocality", aiProcess_ImproveCacheLocality },
	{ "aiProcess_RemoveRedundantMaterials", aiProcess_RemoveRedundantMaterials },
	{ "aiProcess_FixInfacingNormals", aiProcess_FixInfacingNormals },
	{ "aiProcess_PopulateArmatureData", aiProcess_PopulateArmatureData },
	{ "aiProcess_SortByPType", aiProcess_SortByPType },
	{ "aiProcess_FindDegenerates", aiProcess_FindDegenerates },
	{ "aiProcess_FindInvalidData", aiProcess_FindInvalidData },
	{ "aiProcess_GenUVCoords", aiProcess_GenUVCoords },
	{ "aiProcess_TransformUVCoords", aiProcess_TransformUVCoords },
	{ "aiProcess_FindInstances", aiProcess_FindInstances },
	{ "aiProcess_OptimizeMeshes", aiProcess_OptimizeMeshes },
	{ "aiProcess_OptimizeGraph", aiProcess_OptimizeGraph },
	{ "aiProcess_FlipUVs", aiProcess_FlipUVs },
	{ "aiProcess_FlipWindingOrder", aiProcess_FlipWindingOrder },
	{ "aiProcess_SplitByBoneCount", aiProcess_SplitByBoneCount },
	{ "aiProcess_Debone", aiProcess_Debone },
	{ "aiProcess_GlobalScale", aiProcess_GlobalScale },
	{ "aiProcess_EmbedTextures", aiProcess_EmbedTextures },
	{ "aiProcess_ForceGenNormals", aiProcess_ForceGenNormals },
	{ "aiProcess_DropNormals", aiProcess_DropNormals },
	{ "aiProcess_GenBoundingBoxes", aiProcess_GenBoundingBoxes },
	{ "aiProcess_ConvertToLeftHanded", aiProcess_ConvertToLeftHanded },
	{ "aiProcessPreset_TargetRealtime_Fast", aiProcessPreset_TargetRealtime_Fast },
	{ "aiProcessPreset_TargetRealtime_Quality", aiProcessPreset_TargetRealtime_Quality },
	{ "aiProcessPreset_TargetRealtime_MaxQuality", aiProcessPreset_TargetRealtime_MaxQuality }
};
